### ISSUE TITLE
Deployment fails with env secrets

### ISSUE THREAD

**Issue by lsalehar** [reflex-dev/reflex-deploy-action#9]
Hi

I'm trying to get my project to deploy with this github action:
```
name: Deploy Aero Data Reflex

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v1
        with:
          auth_token: ${{ secrets.REFLEX_AUTH_TOKEN }}
          project_id: ${{ secrets.REFLEX_PROJECT_ID }}
          extra_args: "--env SUPABASE_URL=${{ secrets.SUPABASE_URL }} --env SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}"
          python_version: "3.12"
```

I have defined them in my secrets in github project settings and checked three times they have a value and are correct, but my deploy action keeps failing with:
```
──────────────────────────── Initializing aero_data ────────────────────────────
[11:44:00] Initializing the web directory.                        console.py:161
Success: Initialized aero_data
────────────── Compiling production app and preparing for export. ──────────────
Zipping Backend: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 39/39 0:00:00
────────────── Compiling production app and preparing for export. ──────────────
Unable to export due to: SUPABASE_URL not found. Declare it as envvar or define 
a default value.
Error: Process completed with exit code 1.
```
My github project does contain .env.example file but I guess that does not affect the deployment process. I have no idea on how to figure out why this is failing.

**Comment by lsalehar** [comment]
This however works:
```
      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v1
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        with:
          auth_token: ${{ secrets.REFLEX_AUTH_TOKEN }}
          project_id: ${{ secrets.REFLEX_PROJECT_ID }}
          python_version: "3.12"
```
